'use client';

interface AISummaryCardProps {
  summary: string;
  bulletPoints?: string[];
  actionItems?: string[];
  type?: string;
  loading?: boolean;
  onRefresh?: () => void;
}

export function AISummaryCard({
  summary,
  bulletPoints = [],
  actionItems = [],
  type = 'summary',
  loading = false,
  onRefresh,
}: AISummaryCardProps) {
  if (loading) {
    return (
      <div className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-4 animate-pulse">
        <div className="flex items-center gap-2 mb-3">
          <div className="w-5 h-5 rounded-full bg-[var(--color-border)]" />
          <div className="h-3 w-24 rounded bg-[var(--color-border)]" />
        </div>
        <div className="space-y-2">
          <div className="h-3 w-full rounded bg-[var(--color-border)]" />
          <div className="h-3 w-4/5 rounded bg-[var(--color-border)]" />
          <div className="h-3 w-3/5 rounded bg-[var(--color-border)]" />
        </div>
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-4">
      {/* Header */}
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded-full bg-gradient-to-br from-[var(--color-primary)] to-purple-500 flex items-center justify-center">
            <span className="material-symbols-outlined text-white" style={{ fontSize: '12px' }}>auto_awesome</span>
          </div>
          <span className="text-xs font-semibold text-[var(--color-text-muted)] uppercase tracking-wider">
            AI Summary · {type}
          </span>
        </div>
        {onRefresh && (
          <button
            onClick={onRefresh}
            className="text-[var(--color-text-muted)] hover:text-[var(--color-primary)] transition-colors cursor-pointer"
          >
            <span className="material-symbols-outlined text-base">refresh</span>
          </button>
        )}
      </div>

      {/* Summary */}
      <p className="text-sm text-[var(--color-text)] leading-relaxed mb-3">{summary}</p>

      {/* Bullet points */}
      {bulletPoints.length > 0 && (
        <div className="space-y-1.5 mb-3">
          {bulletPoints.map((point, i) => (
            <div key={i} className="flex items-start gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-[var(--color-primary)] mt-1.5 shrink-0" />
              <p className="text-xs text-[var(--color-text-muted)]">{point}</p>
            </div>
          ))}
        </div>
      )}

      {/* Action items */}
      {actionItems.length > 0 && (
        <div className="border-t border-[var(--color-border)] pt-3">
          <p className="text-xs font-semibold text-[var(--color-text-muted)] uppercase tracking-wider mb-2">
            Action Items
          </p>
          <div className="space-y-1.5">
            {actionItems.map((item, i) => (
              <div key={i} className="flex items-start gap-2">
                <span className="material-symbols-outlined text-[var(--color-primary)] shrink-0" style={{ fontSize: '14px' }}>
                  task_alt
                </span>
                <p className="text-xs text-[var(--color-text)]">{item}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Footer */}
      <p className="text-[10px] text-[var(--color-text-muted)] mt-3">
        Generated by WeEverything AI · May contain inaccuracies
      </p>
    </div>
  );
}
